services:
  web-dav:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - USERNAME=${USERNAME} # Set as environment variable.
      - PASSWORD=${PASSWORD} # Set as environment variable.
    volumes:
      - ./data:/data